#!/usr/bin/env bash
# script that sets port to 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/8080/80/' /etc/nginx/sites-available/default
service nginx start
