#!/usr/bin/env bash
# Prints "Best School" 10 times, but on the 9th iteration, displays "Hi" on a new line
n=0
while ((n < 10)); do
	echo "Best School"
	if ((n == 8)); then
		echo "Hi"
	fi
	n=$((n+1))
done
