#!/usr/bin/env bash
# Displays numbers 1 to 20, on 4th iteration displays 4 and then "bad luck from China", on 9th iteration displays 9 and then "bad luck from Japan" and on 17th iteration displays 17 and then "bad luck from Italy"
n=1
while ((n <= 20)); do
	echo "$n"
	case $n in
		4)
			echo "bad luck from China"
		;;
		9)
			echo "bad luck from Japan"
		;;
		17)
			echo "bad luck from Italy"
		;;
	esac
	n=$((n+1))
done
